Обновленная статья SurfMVP
surfstudio/Surf-iOS-Developers pull request #23
Opened 2020-01-08 18:30 UTC by fixique

Обсуждали с @gregoryvit, что можно было бы обновить статью SurfMVP в рамках новых статей по архитектурам от Филимонова и меня. 

1. Обновил картинки в SurfMVP, потому что в статье про координаторы планирую использовать свои, и чтобы сохранить единообразие добавил из своей статьи. 
2. Поправил формулировки в тексте в некоторых местах, часть текста брал из своей стати, которую проверяла Аня и Гриша. 
3. Убрал подход, что адаптер инициализируется в конфигураторе, сколько проектов видел, нигде так не делаем, а стажеры приходят и заносят из документации. 
4. Дописал про подход с адаптерами, что все таки не везде используется AdapterOutput. Тоже время от времени приходилось проговаривать со стажерами и на онбординге. 
5. Постарался поправить компоновку текста, чтобы было более удобно читать, если честно, то я терялся, когда первый раз читал.

2020-01-09 10:56 UTC, gregoryvit requested changes
Очень круто!

Давай еще:

- [x] Уберем в спойлеры замечания. См. комменты к коду
- [x] И еще не очень уверен про кусок со структурой проекта. Может его тоже переделать?

2020-01-09 10:56 UTC, gregoryvit commented on Surf_MVP.md
> +[**Внимание! правила наименования методов в протоколах ViewInput и ViewOutput**](#правила-наименования-методов-viewinput-и-viewoutput)
Думаешь лучше в конец статьи вынести? Давай под спойлер может уберем (как здесь https://github.com/surfstudio/SwiftCodestyle)?

2020-01-09 10:56 UTC, gregoryvit commented on Surf_MVP.md
> +[**Внимание! правила наименования методов в протоколе RouterInput**](#правила-наименования-методов-в-протоколе-routerinput)
Аналогично. Предлагаю вынести под спойлер

2020-01-09 11:59 UTC, fixique commented on Surf_MVP.md
> +[**Внимание! правила наименования методов в протоколах ViewInput и ViewOutput**](#правила-наименования-методов-viewinput-и-viewoutput)
О, хорошая идея. Исправлю позже

2020-01-09 21:09 UTC, fixique commented
> Очень круто!
> 
> Давай еще:
> 
> * [x]  Уберем в спойлеры замечания. См. комменты к коду
> * [x]  И еще не очень уверен про кусок со структурой проекта. Может его тоже переделать?

1. Сделал спойлеры для замечаний. 
2. Не очень придумал что сделать со структурой проекта. Спрятал ее тоже под спойлер. 
Не понял именно ты хочешь ее поменять совсем или тоже просто спрятать? 
Ибо вроде структура на новых проектах примерно такая. 

Как вариант удалить ее отсюда вообще и перенести в шаблоны. Но тогда там надо для всех шаблонов структуру описать, но не уверен, что это нужно вообще. 

Возможно лучший вариант – это удалить ее, ибо поддерживать текстовое описание структуры проекта сложновато, да и при условиях, что все шаблоны в другом репозитории. 
Смысл если ты особо не задумываешься о структуре и просто инитишься из шаблона. 
Плюс, к тому чтобы удалить ее вообще, это тот факт, что к архитектурному паттерну структура проекта никак не относится)

2020-01-13 07:12 UTC, gregoryvit requested changes
Давай немного спойлеры обновим и сольем

2020-01-13 07:12 UTC, gregoryvit commented on Surf_MVP.md
> +<details>
Давай так лучше

```suggestion
<details>
<summary>Правила наименования методов ViewInput и ViewOutput</summary>
```

2020-01-13 07:12 UTC, gregoryvit commented on Surf_MVP.md
> +##### Правила наименования методов ViewInput и ViewOutput
```suggestion
```

2020-01-13 07:12 UTC, gregoryvit commented on Surf_MVP.md
> +##### Правила наименования методов в протоколе RouterInput
Аналогично
```suggestion
```

2020-01-13 07:12 UTC, gregoryvit commented on Surf_MVP.md
> +<details>
```suggestion
<details>
<summary>Правила наименования методов в протоколе RouterInput</summary>
```

2020-01-13 07:12 UTC, gregoryvit commented on Surf_MVP.md
> +<details>
```suggestion
<details>
<summary>Структура проекта</summary>
```

2020-01-13 07:22 UTC, gregoryvit commented
> Возможно лучший вариант – это удалить ее, ибо поддерживать текстовое описание структуры проекта сложновато, да и при условиях, что все шаблоны в другом репозитории.
> Смысл если ты особо не задумываешься о структуре и просто инитишься из шаблона.
> Плюс, к тому чтобы удалить ее вообще, это тот факт, что к архитектурному паттерну структура проекта никак не относится)

Давай удалим!

2020-01-20 12:07 UTC, gregoryvit approved these changes
Все отлично

2020-01-20 12:07 UTC, merged